c_store/api/urls.py
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from api.views import (
    AltDeleteItemsSerialViews,
    CategoryViewSet,
    DeleteItemsSerialViews,
    ItemViewSet,
    NameViewSet,
    PostItemsSerialViews
)

app_name = 'api'


router_v1 = DefaultRouter()
router_v1.register('category', CategoryViewSet, 'category')
router_v1.register('item', ItemViewSet, 'item')
router_v1.register('name', NameViewSet, 'name')

schema_view = get_schema_view(
   openapi.Info(
      title="Store API",
      default_version='v1',
      description="Документация для приложения store проекта Store",
      # terms_of_service="URL страницы с пользовательским соглашением",
      contact=openapi.Contact(email="ee@ya.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('v1/post_items_serial/<name_id>/',
         PostItemsSerialViews.as_view(), name='post_items_serial'),
    path('v1/delete_items_serial/',
         DeleteItemsSerialViews.as_view(), name='delete_items_serial'),
    path('v1/alt_delete_items_serial/',
         AltDeleteItemsSerialViews.as_view(), name='alt_delete_items_serial'),
    path('v1/', include(router_v1.urls)),
]
urlpatterns += [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] 

c_store/c_store/urls.py
# my_project_6 URL Configuration
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('api/', include('api.urls', namespace='api')),
    path('', include('store.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

c_store/store/urls.py
#my_project_6/main_app

from django.urls import path

from store import views

app_name = 'store'



urlpatterns = [
    path('', views.index, name='index'),
    # path('store/', views.store_catalog),
    path('store/item/<int:item_id>/', views.item_detail, name='item_detail'),
    path('store/item/<int:item_id>/edit/', views.item_edit, name='item_edit'),
    path('store/item/order/<int:name_id>/', views.order, name='item_order'),
    path('store/create_item/', views.item_create, name='item_create'),
    path('store/name/<int:name_id>/', views.name_detail, name='name_detail'),
    path('store/name/<int:name_id>/edit/', views.name_edit, name='name_edit'),
    path('store/create_name/', views.name_create, name='name_create'),
    path('store/category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('store/category/<int:category_id>/edit/', views.category_edit, name='category_edit'),
    path('store/create_category/', views.category_create, name='category_create'),
    path('store/all_categories/', views.all_categories, name='all_categories'),
    path('store/staff_panel/', views.staff_panel, name='staff_panel'),
]

c_store/users/urls.py
# users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView
)
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change_form/',
         PasswordChangeView.
         as_view(template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_change_done/',
         PasswordChangeDoneView.
         as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset_form/',
         PasswordResetView.
         as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.
         as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.
         as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_comfirm'),
    path('reset/done/',
         PasswordResetCompleteView.
         as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

c_store/templates/includes/footer.html
<!DOCTYPE html>
<p>© <span style="color:black">{% now "Y" %}</span> <span style="color:red">My</span><span style="color:black"> magazine</span></p>

c_store/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
<nav class="navbar navbar-light" 
style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{%url 'store:index'%}">
      <img src="{% static 'img/logo.png' %}" 
      width="30" height="30" 
      class="d-inline-block align-top" alt="">
      <span style="color:red">My</span> store
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">

      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'store:all_categories' %}active
        {% endif %}"href="{% url 'store:all_categories' %}">category</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'store:index' %}active
        {% endif %}"href="{% url 'store:index' %}">index</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light"
        href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light"
        href="{% url 'users:logout'%}">Выйти</a>
      </li>
      <li>
        User: {{ user.username }}
      <li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light" 
        href="{% url 'users:login'%}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" 
        href="{% url 'users:signup'%}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
    {% endwith %}
  </div>
</nav>      

c_store/templates/includes/header_staff.html
<!DOCTYPE html>
{% load static %}
<nav class="navbar navbar-light" 
style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{%url 'store:index'%}">
      <img src="{% static 'img/logo.png' %}" 
      width="30" height="30" 
      class="d-inline-block align-top" alt="">
      <span style="color:red">My</span> store
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">

      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'store:item_create' %}active
        {% endif %}"href="{% url 'store:item_create' %}">Создать товар</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'store:category_create' %}active
        {% endif %}"href="{% url 'store:category_create' %}">Создать категорию</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'store:name_create' %}active
        {% endif %}"href="{% url 'store:name_create' %}">Создать модель</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light"
        href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light"
        href="{% url 'users:logout'%}">Выйти</a>
      </li>
      <li>
        User: {{ user.username }}
      <li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light" 
        href="{% url 'users:login'%}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" 
        href="{% url 'users:signup'%}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
    {% endwith %}
  </div>
</nav>      