c_store/api/urls.py
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from api.views import (
    AltDeleteItemsSerialViews,
    CategoryViewSet,
    DeleteItemsSerialViews,
    ItemViewSet,
    NameViewSet,
    PostItemsSerialViews
)

app_name = 'api'


router_v1 = DefaultRouter()
router_v1.register('category', CategoryViewSet, 'category')
router_v1.register('item', ItemViewSet, 'item')
router_v1.register('name', NameViewSet, 'name')

schema_view = get_schema_view(
   openapi.Info(
      title="Store API",
      default_version='v1',
      description="Документация для приложения store проекта Store",
      # terms_of_service="URL страницы с пользовательским соглашением",
      contact=openapi.Contact(email="ee@ya.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('v1/post_items_serial/<name_id>/',
         PostItemsSerialViews.as_view(), name='post_items_serial'),
    path('v1/delete_items_serial/',
         DeleteItemsSerialViews.as_view(), name='delete_items_serial'),
    path('v1/alt_delete_items_serial/',
         AltDeleteItemsSerialViews.as_view(), name='alt_delete_items_serial'),
    path('v1/', include(router_v1.urls)),
]
urlpatterns += [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] 

c_store/c_store/urls.py
# my_project_6 URL Configuration
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('api/', include('api.urls', namespace='api')),
    path('', include('store.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

c_store/store/urls.py
#my_project_6/main_app

from django.urls import path

from store import views

app_name = 'store'



urlpatterns = [
    path('', views.index, name='index'),
    # path('store/', views.store_catalog),
    path('store/item/<int:item_id>/', views.item_detail, name='item_detail'),
    path('store/item/<int:item_id>/edit/', views.item_edit, name='item_edit'),
    path('store/item/order/<int:name_id>/', views.order, name='item_order'),
    path('store/create_item/', views.item_create, name='item_create'),
    path('store/name/<int:name_id>/', views.name_detail, name='name_detail'),
    path('store/name/<int:name_id>/edit/', views.name_edit, name='name_edit'),
    path('store/create_name/', views.name_create, name='name_create'),
    path('store/category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('store/category/<int:category_id>/edit/', views.category_edit, name='category_edit'),
    path('store/create_category/', views.category_create, name='category_create'),
    path('store/all_categories/', views.all_categories, name='all_categories'),
    path('store/staff_panel/', views.staff_panel, name='staff_panel'),
]

c_store/store/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

class Category(models.Model):
    title = models.CharField('Категория', max_length=64)
    description = models.TextField('Описание Категории', max_length=256)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        default_related_name = 'category'

    def __str__(self):
        return self.title

class Name(models.Model):
    mod_name = models.CharField('Модель товара', max_length=64)
    price=models.PositiveIntegerField('Цена', help_text='Цена товара', blank=True, null=True) 
    mod_detail = models.TextField('Описание Товара', max_length=256)
    mod_date = models.DateTimeField('Дата обновления', auto_now=True, null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Категория',
        help_text='Выберите категорию',
        related_name='category_name'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='store/',
        blank=True
    )

    class Meta:
        verbose_name = 'Молель товара'
        verbose_name_plural = 'Модели товаров'
        default_related_name = 'item_model'

    def __str__(self):
        return self.mod_name

class Item(models.Model):
    STATUS = [
        ('Warehouse', 'Warehouse'),
        ('Store', 'Store'),
        ('In_magaz', 'From warehouse in store'),
        ('Order', 'Order and wait proccesing'),
        ('Wait', 'Wait purchase'),
        ('Sold', 'Sold in magazine'),
    ]
    name = models.ForeignKey(
        Name,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Модель',
        help_text='Модель товара',
        related_name='model_items'
    )

    serial_num=models.CharField('Серийный номер', max_length=12, blank=True, null=True, unique=True)
    status= models.CharField('Место нахожднения/Статус', max_length=32, choices=STATUS, default='Store')
    phone=models.CharField('Номер телефона и имя', max_length=64, blank=True, null=True,)
    pub_date = models.DateTimeField('Дата обновления', auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null = True,
        verbose_name='Автор',
        related_name='items'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
    
    def __str__(self):
        return self.name.mod_name

c_store/store/forms.py
from django import forms

from store.models import Category, Item, Name


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'serial_num', 'status', 'phone',)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'description',)

class NameForm(forms.ModelForm):
    class Meta:
        model = Name
        fields = ('mod_name', 'price', 'mod_detail', 'category', 'image',)
        
class PhoneItemForm(ItemForm):
    class Meta:
        model = Item
        fields = ('phone',)

c_store/store/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import UpdateView

from store.forms import CategoryForm, ItemForm, NameForm, PhoneItemForm
from store.models import Category, Item, Name
from store.time_func import timeit


@timeit
def index(request):
    template = 'store/index.html'
    text = 'Это главная страница проекта Store'
    last_items = Item.objects.filter(status='Store').order_by('-pub_date')[:10]
    context = {
        'last_items': last_items,
        'text': text,
        # 'page_obj': page_obj,
    }
    return render(request, template, context)

@timeit
def item_detail(request, item_id):
    template = 'store/one_item_full.html'
    text = '___carr_item____'
    curr_item = Item.objects.select_related('name',).get(id=item_id)
    context = {
        'curr_item': curr_item,
        'text': text,
        # 'page_obj': page_obj,
    }
    return render(request, template, context)

@timeit
@login_required()
@permission_required('store.change_item', raise_exception=True)
def item_edit(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    form = ItemForm(
        request.POST or None,
        files=request.FILES or None,
        instance=item
    )
    if form.is_valid():
        form.save()
        return redirect('store:item_detail', item_id=item_id)
    context = {
        'item': item,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'store/create_item.html', context) 

@timeit
@login_required()
@permission_required('store.add_item', raise_exception=True)
def item_create(request):
    template = 'store/create_item.html'
    form = ItemForm(request.POST, files=request.FILES or None)
    is_edit = False
    if form.is_valid():
        item = form.save(commit=False)
        item.author = request.user
        item.save()
        return redirect('store:item_detail', item.id)
    return render(request, template, {'form': form, is_edit: is_edit})

@timeit
def name_detail(request, name_id):
    template = 'store/one_name_full.html'
    text = '___Name_detail____'
    # name = Name.objects.prefetch_related('model_items').get(id=name_id)
    name = Name.objects.get(id=name_id)
    item_in_store = name.model_items.filter(status ='Store')
    context = {
        'item_in_store': item_in_store,
        'name': name,
        'text': text,
        # 'page_obj': page_obj,
    }
    return render(request, template, context)

@timeit
@login_required()
@permission_required('store.change_name', raise_exception=True)
def name_edit(request, name_id):
    name = get_object_or_404(Name, id=name_id)
    form = NameForm(
        request.POST or None,
        files=request.FILES or None,
        instance=name
    )
    if form.is_valid():
        form.save()
        return redirect('store:name_detail', name_id=name_id)
    context = {
        'name': name,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'store/create_name.html', context) 

@timeit
@login_required()
@permission_required('store.add_name', raise_exception=True)
def name_create(request):
    template = 'store/create_name.html'
    form = NameForm(request.POST, files=request.FILES or None)
    is_edit = False
    if form.is_valid():
        name = form.save(commit=False)
        name.author = request.user
        name.save()
        # return redirect('store:name_detail', name.id)
        return redirect('store:index')
    return render(request, template, {'form': form, is_edit: is_edit})

@timeit
def category_detail(request, category_id):
    template = 'store/one_category_full.html'
    text = '___carr_category____'
    category = Category.objects.get(id=category_id)
    category_names = category.category_name.all()[:10]
    context = {
        'names': category_names,
        'category': category,
        'text': text,
        # 'page_obj': page_obj,
    }
    return render(request, template, context)

@timeit
@login_required()
@permission_required('store.change_category', raise_exception=True)
def category_edit(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    form = CategoryForm(
        request.POST or None,
        files=request.FILES or None,
        instance=category
    )
    if form.is_valid():
        form.save()
        return redirect('store:category_detail', category_id=category_id)
    context = {
        'category': category,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'store/create_category.html', context) 

@timeit
@login_required()
@permission_required('store.add_category', raise_exception=True)
def category_create(request):
    template = 'store/create_category.html'
    form = CategoryForm(request.POST, files=request.FILES or None)
    is_edit = False
    if form.is_valid():
        name = form.save(commit=False)
        name.author = request.user
        name.save()
        # return redirect('store:category_detail', name.id)
        return redirect('store:index')
    return render(request, template, {'form': form, is_edit: is_edit})


@timeit
def order(request, name_id):
    template = 'store/order.html'
    text = 'Заказ товара.'
    try:
        item = Item.objects.filter(status='Store', name=name_id)[0]
        item_id = item.id
    except:
        return render(request, 'store/result_text.html', {'text': 'Товара нет в наличии!'}) 
    form = PhoneItemForm(
        request.POST or None,
        files=request.FILES or None,
        instance=item
    )
    if form.is_valid():
        form.save()
        item.status = 'Order'
        item.save()
        return render(request, 'store/result_text.html', {'text': 'Товар заказан!'}) 
    context = {
        'item': item,
        'form': form,
        'name_id': name_id,
        'is_edit': True,
    }
    return render(request, template, context) 

@timeit
def all_categories(request):
    template = 'store/all_categories.html'
    text = 'Все категории товаров'
    all_categories = Category.objects.all()[:10]
    context = {
        'all_categories': all_categories,
        'text': text,
        # 'page_obj': page_obj,
    }
    return render(request, template, context)

@timeit
@login_required()
@permission_required('store.add_name', raise_exception=True)
def staff_panel(request):
    template = 'store/staff_panel.html'
    text = 'Веб страница для сотрудников и администрирования.'
    last_items = Item.objects.filter(status='Order').order_by('pub_date')[:10]
    context = {
        'last_items': last_items,
        'text': text,
        # 'page_obj': page_obj,
    }
    return render(request, template, context)

c_store/templates/store/all_categories.html
{% extends 'base.html' %}
{% block title %}Категории{% endblock %}
{% block content %}
<h1>{{ text }} – My magazine. </h1>
<h4> Список категорий </h4>
<p>
    {% for category in all_categories %}
    <b>{{category}}</b>
    <b>{{ category.description|linebreaksbr }}: </b>
    <object> <a href="{% url 'store:category_detail' category.id %}"><b> Просмотреть </b> </a> </object>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
</p>
{% endblock %}

c_store/templates/store/create_category.html
<!DOCTYPE html> 
{% extends 'base_staff.html' %}
{% block title %}
  {% if is_edit %}Редактируем категорию{% else %}Создаем новую категорию{% endif %}
{% endblock %}
{% block content %}
  <body>	   
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Новая категория
                {% endif %}         
              </div>
              {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
                {% endfor %}
              {% endif %}
              <div class="card-body">        
                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" 
                  action="{% url 'store:category_edit' category.id %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data" 
                  action="{% url 'store:category_create' %}">
                {% endif %}
                  {% csrf_token %}
        
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Категория                 
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.title }}
                    <small id="id_text-help" class="form-text text-muted">
                      Название категории
                    </small>                  
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Описание                
                    </label>
                    {{ form.description }}
                    <small id="id_group-help" class="form-text text-muted">
                      Описание категории
                    </small>
                  </div>

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                     {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
{% endblock %}
</html>

c_store/templates/store/create_item.html
<!DOCTYPE html> 
{% extends 'base_staff.html' %}
{% block title %}
  {% if is_edit %}Редактируем товар{% else %}Создаем новый товар{% endif %}
{% endblock %}
{% block content %}
  <body>	   
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Новый товар
                {% endif %}         
              </div>
              {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
                {% endfor %}
              {% endif %}
              <div class="card-body">        
                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" 
                  action="{% url 'store:item_edit' item.id %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data" 
                  action="{% url 'store:item_create' %}">
                {% endif %}
                  {% csrf_token %}
        
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Модель                 
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.name }}
                    <small id="id_text-help" class="form-text text-muted">
                      Название модели
                    </small>                  
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Серийный номер                 
                    </label>
                    {{ form.serial_num }}
                    <small id="id_group-help" class="form-text text-muted">
                      Серийный номер
                    </small>
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Статус                 
                    </label>
                    {{ form.status }}
                    <small id="id_group-help" class="form-text text-muted">
                      Статус
                    </small>
                  </div>

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                     {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
{% endblock %}
</html>

c_store/templates/store/create_name.html
<!DOCTYPE html> 
{% extends 'base_staff.html' %}
{% block title %}
  {% if is_edit %}Редактируем товар{% else %}Создаем новый товар{% endif %}
{% endblock %}
{% block content %}
  <body>	   
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Новый товар
                {% endif %}         
              </div>
              {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
                {% endfor %}
              {% endif %}
              <div class="card-body">        
                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" 
                  action="{% url 'store:name_edit' name.id %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data" 
                  action="{% url 'store:name_create' %}">
                {% endif %}
                  {% csrf_token %}
        
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Модель                 
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.mod_name }}
                    <small id="id_text-help" class="form-text text-muted">
                      Название модели
                    </small>                  
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Цена                 
                    </label>
                    {{ form.price }}
                    <small id="id_group-help" class="form-text text-muted">
                      Цена
                    </small>
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Детали                 
                    </label>
                    {{ form.mod_detail }}
                    <small id="id_group-help" class="form-text text-muted">
                      Детали модели
                    </small>
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Категория                  
                    </label>
                    {{ form.category }}
                    <small id="id_group-help" class="form-text text-muted">
                      Категория, к которой относиться товар
                    </small>
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      image                  
                    </label>
                    {{ form.image }}
                    <small id="id_image-help" class="form-text text-muted">
                      Картинка
                    </small>
                  </div>

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                     {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
{% endblock %}
</html>

c_store/templates/store/index.html
{% extends 'base.html' %}
{% block title %}Основная страница{% endblock %}
{% block content %}
<h1>{{ text }}</h1>
<h4> Новые поступления: </h4>
{% for item in last_items %}
{% include 'store/includes/one_item_short.html' %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}

c_store/templates/store/one_category_full.html
{% extends 'base.html' %}
{% block title %}Основная страница{% endblock %}
{% load thumbnail %}
{% block content %}
<h1>{{ text }} – My store. </h1>
<h4> Описание модели </h4>
<p><b>{{category}}</b>
    <b>{{ category.description }}: </b>
    {% for name in names %}
    
    {% include 'store/includes/one_name_short.html' %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
</p>
{% endblock %}

c_store/templates/store/one_item_full.html
{% extends 'base.html' %}
{% block title %}Основная страница{% endblock %}
{% load thumbnail %}
{% block content %}
<h1>{{ text }} – My store. </h1>
<h4> Описание экземпляра </h4>
<p>
    <b>{{curr_item.name.category}}</b>
    <b>{{ curr_item }} </b>
    , статус: <b>{{curr_item.status}}</b>
    , цена: <b>{{curr_item.name.price}}</b> руб.
    , дата добавления модели: <b>{{curr_item.name.mod_date}}</b>
    <object> <a href="{% url 'store:item_order' curr_item.name.id %}"><b> Заказать </b> </a> </object>
    {% thumbnail curr_item.name.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
</p>
{% endblock %}

c_store/templates/store/one_name_full.html
{% extends 'base.html' %}
{% block title %}Основная страница{% endblock %}
{% load thumbnail %}
{% block content %}
<h1>{{ text }} – My store. </h1>
<h4> Описание модели </h4>
<p>
    <b>{{name.category}}</b>
    <b>{{ name }} </b>
    , цена: <b>{{name.price}}</b> руб.
    , дата добавления модели: <b>{{name.mod_date}}</b>
    , в магазине: <b>{{item_in_magaz|length}}</b>
    , на складе: <b>{{item_in_store|length}}</b>
    {% thumbnail name.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    Описание модели: <b>{{name.mod_detail}}</b>
</p>
{% endblock %}

c_store/templates/store/order.html
{% extends 'base.html' %}
{% block title %}Заказ товара{% endblock %}
{% block content %}
<h1>{{ text }} – My store. </h1>
{% include 'store/includes/one_item_short.html' %}
<form method="POST" action="{% url 'store:item_order' name_id %}">
    {% csrf_token %}
    <p>Введите номер телефона и Ваше имя:</p> 
    {{ form.as_p }}
    <input type="submit" value="Заказать">
</form> 
{% endblock %}

c_store/templates/store/result_text.html
{% extends 'base.html' %}
{% block title %}Заказ товара{% endblock %}
{% block content %}
<h1>Ответ – My store. </h1>

    <p>{{ text }}</p> 

{% endblock %}

c_store/templates/store/staff_panel.html
{% extends 'base_staff.html' %}
{% block title %}Основная страница{% endblock %}
{% block content %}
<h1>{{ text }} </h1>
<h4> Последний заказанный товар: </h4>
{% for item in last_items %}
{% include 'store/includes/one_item_short.html' %}
<object> <a href="{% url 'store:item_edit' item.id %}"><b> Редактировать товар </b> </a> </object> &emsp;
<object> <a href="{% url 'store:name_edit' item.name.id %}"><b> Редактировать модель </b> </a> </object> &emsp;
<object> <a href="{% url 'store:category_edit' item.name.category.id %}"><b> Редактировать категорию </b> </a> </object>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}