c_store/api/urls.py
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from api.views import (
    AltDeleteItemsSerialViews,
    CategoryViewSet,
    DeleteItemsSerialViews,
    ItemViewSet,
    NameViewSet,
    PostItemsSerialViews
)

app_name = 'api'


router_v1 = DefaultRouter()
router_v1.register('category', CategoryViewSet, 'category')
router_v1.register('item', ItemViewSet, 'item')
router_v1.register('name', NameViewSet, 'name')

schema_view = get_schema_view(
   openapi.Info(
      title="Store API",
      default_version='v1',
      description="Документация для приложения store проекта Store",
      # terms_of_service="URL страницы с пользовательским соглашением",
      contact=openapi.Contact(email="ee@ya.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('v1/post_items_serial/<name_id>/',
         PostItemsSerialViews.as_view(), name='post_items_serial'),
    path('v1/delete_items_serial/',
         DeleteItemsSerialViews.as_view(), name='delete_items_serial'),
    path('v1/alt_delete_items_serial/',
         AltDeleteItemsSerialViews.as_view(), name='alt_delete_items_serial'),
    path('v1/', include(router_v1.urls)),
]
urlpatterns += [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] 

c_store/c_store/urls.py
# my_project_6 URL Configuration
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('api/', include('api.urls', namespace='api')),
    path('', include('store.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

c_store/users/urls.py
# users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView
)
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change_form/',
         PasswordChangeView.
         as_view(template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_change_done/',
         PasswordChangeDoneView.
         as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset_form/',
         PasswordResetView.
         as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.
         as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.
         as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_comfirm'),
    path('reset/done/',
         PasswordResetCompleteView.
         as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

c_store/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

c_store/users/views.py
# users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('store:index')
    template_name = 'users/signup.html'

c_store/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

c_store/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help"
                  class="form-text text-muted">
                  {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

c_store/templates/users/password_change_done.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}
</html>

c_store/templates/users/password_change_form.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block title %}Меняем пароль{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action=
            "{% url 'users:password_change_form' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="old_password" 
                autofocus class="form-control" 
                required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password1"
                class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help"
                  class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим 
                    именем или другой персональной информацией или 
                    быть слишком похожим на неё.</li>
                    <li>Ваш пароль должен содержать как минимум 8 
                    символов.</li><li>Ваш пароль не может быть одним 
                    из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.
                    </li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password2" 
                class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %} 
</html>

c_store/templates/users/password_reset_complete.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block title %}Восстановление пароля завершено{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="../users/login.html">войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}
</html>

c_store/templates/users/password_reset_confirm.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block title %}Подтверждение нового пароля{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" 
                action="../users/lpassword_reset_confirm.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" 
                    class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help"
                    class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим 
                      именем или другой персональной информацией или быть 
                      слишком похожим на неё.</li><li>Ваш пароль должен 
                      содержать как минимум 8 символов.</li><li>Ваш пароль 
                      не может быть одним из широко распространённых паролей.
                      </li><li>Ваш пароль не может состоять только из цифр.
                      </li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" 
                    class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
      </div>
{% endblock %} 
</html>

c_store/templates/users/password_reset_done.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block title %}Отправлено письмо{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо 
            со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %} 
</html>

c_store/templates/users/password_reset_form.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block title %}Форма сброса пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес 
            электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_reset' %}">
            {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254"
                class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %} 
</html>

c_store/templates/users/signup.html
<!-- templates/users/signup.html -->

{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 